spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/miniautorizador}
    username: root
    password:
#    tomcat:
#      max-active: 500000
#      initial-size: 400000
#    hikari:
#      maximum-pool-size: 500000
#      max-lifetime: 500000

server:
  error:
    include-stacktrace: never
  port: 8080

spring-doc:
  swagger-ui:
    path: /
    tagsSorter: alpha
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus