scrape_configs:
  - job_name: 'mini-autorizador input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.15.97:8080'] #colocar o ip da maquina local:8080
        labels:
          application: 'Mini Autorizador'